name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
          
      - run: flutter --version
      
      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build web
        run: flutter build web

      - name: Publish app
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.TARGET_SERVER_USER }}
            server: ${{ secrets.TARGET_SERVER }}
            local_path: './src/build/web/*'
            remote_path: 'ffmpeg.chrishibler.com'
            sftp_only: true
            password: ${{ secrets.TARGET_SERVER_PASSWORD }}